apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gateway.fullname" . | quote }}  # Добавлен quote
spec:
  rules:
    - host: {{ .Values.ingress.hosts[0].host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.hosts[0].paths[0] | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "gateway.fullname" . | quote }}
                port:
                  number: {{ .Values.service.port }}
